import {CONFIDENT_CHECK_ROUTE, CURRENT_RELATIONSHIP_ROUTE, TEST_BEGINNING_ROUTE} from "../routes.constants";

export enum ProgressBarState {
    FILLED='filled',
    UNFILLED='unfilled'
}

export const PROGRESS_BAR_ROUTES:string[]=
   [TEST_BEGINNING_ROUTE, CONFIDENT_CHECK_ROUTE,CURRENT_RELATIONSHIP_ROUTE]

